#!/usr/bin/env bash
# ci-walden tenant-interface v5 — generated by ci-walden tenant-init
# stack: declared (declared entry point (ci-walden/interface.json); the interface calls it and propagates its exit code)
# contract: bash at repo root; exit status is the verdict (0 = green)
# regenerating this file on an unchanged repo is a no-op diff
# conformance: sha256:9569edd57db2fc47b928cb53c5bcf5e5c334c4fe769a6c87eb5f1c80e03d236a
set -eo pipefail
export RUSTFLAGS='-D warnings' && cargo fmt --all --check && cargo clippy --workspace --all-targets --all-features -- -D warnings && cargo test --workspace --all-features --no-fail-fast
